heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls: ["http://es-pract8:9200"]
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://nginx-pract8/server-status"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
output.elasticsearch:
  hosts: ["es-pract8:9200"]
